### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by downthecrop** [downthecrop/wegame-tencent-china-opgg#1]
High Prio
- [x] Query Multiple Unique Names in multisearch
- [x] Load indicato
- [x] Ticket error indicator
- [x] Basic profile page
- [x] Clear localstorage button in GUI or make a better way of determining of our ticket is expired
- [x] detailed profile page
- [x] detailed match history popup
- [x] save loaded matches to localstorage
- [x] Area ID selector
- [x] Check to make sure the match div exists on the page before trying to fill (caused by different profiles having saved game)
- [x] WeGame page injection cleanup of Extension GUI
- [x] League Points
- [x] Extension GUI Buttons improvement
- [x] Jump to player match history by selecting them from a detailed page
- [x] default the profile page of the last person searched (Data to localstorage)
- [x] Use "SummonerName" clicks to set search box and submit
- [x] cache slol_id for searched players
- [x] add recently searched players to autocomplete list popup
- [x] Jump from searched play on Multi to their profile
- [x] Change update button and expand buttons to more clearly show what they do.
- [x] Return data for when the user is unranked/has no games player
- [ ] Add Favorite users for profile

Low Prio
- [x] Multisearch requests and paring with JSON like the profile pages (currently they are built into a URLSearchParam)
- [ ] Share button that somehow includes the user data (Too big for URI)
- [ ] Max width for mutliserach

**Comment by downthecrop** [comment]
I've reversed the data flow from 
OLD: WeGame Extension => iFrame
NEW: iFrame => WeGame => iFrame

Although this adds additional messaging it simplifies the GUI and just makes a bit more sense.

**Comment by downthecrop** [comment]
**on playerdetails for profile page just clear matchhistory and most played divs.

**Comment by downthecrop** [comment]
rewrite templates like this https://i.imgur.com/z0Xf5i3.png

**Comment by downthecrop** [comment]
OPGG Chinese Statistics for Champions https://101.qq.com/detail.shtml?ADTAG=cooperation.glzx.web&name=Gangplank&line=top

**Comment by downthecrop** [comment]
Add gold to advanced details

**Comment by downthecrop** [comment]
1/2/2021 I’m putting this on hold for now until I start playing on CN. Mostly perfect other than some redundant templates and not the cleanest implementation of localstorage.
