### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by downthecrop** [downthecrop/wegame-tencent-china-opgg#7]
- [ ] Convert UI to VueJS
- [x] Consolidate messaging system
- [ ] Dark Mode
- [ ] generic message formater (for each argument Object.assign but the current arguments with selected properties must be selected in the function call instead of the function itself selecting them) 
- [ ] Chinese Translations (someone please help!) 
- [ ] Playercard information is missing data? 
- [ ] Previous pages of matches
- [ ] Tier averages is unimplemented
- [x] Clear saved matches (localstorage) button
- [ ] Pin slol_id to recently searched users
- [ ] correct game mode ids/names for data

Bugs
- Dragon/objective count seems to have issues
- I make no money from this which is a bug. Add annoying ads to make money from the great unwashed masses

**Comment by downthecrop** [comment]
Also we need to rebrand.

**Comment by downthecrop** [comment]
Send area_id as an int.

![](https://i.imgur.com/Iz1TwIi.png)

**Comment by Blitzqq** [comment]
Now both mobile or computer wegame api, career is not public also can not find the battle record, do not know what good way
If you use the lcu api, you can only find the login area
